apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/kong-net: "true"
    io.kompose.service: kong-on
  name: kong-on
spec:
  containers:
  - env:
    - name: KONG_ADMIN_ACCESS_LOG
      value: /dev/stdout
    - name: KONG_ADMIN_ERROR_LOG
      value: /dev/stderr
    - name: KONG_ADMIN_LISTEN
      value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    - name: KONG_DATABASE
      value: postgres
    - name: KONG_PG_HOST
      value: kong-db-on
    - name: KONG_PG_PASSWORD
      value: kongPassword123
    - name: KONG_PG_USER
      value: kongUser
    - name: KONG_PROXY_ACCESS_LOG
      value: /dev/stdout
    - name: KONG_PROXY_ERROR_LOG
      value: /dev/stderr
    image: kong:latest
    name: kong-on
    ports:
    - containerPort: 8000
    - containerPort: 8443
    - containerPort: 8001
    - containerPort: 8444
    resources: {}
  restartPolicy: OnFailure
status: {}
