apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/kong-net: "true"
    io.kompose.service: kong-db-migrations-on
  name: kong-db-migrations-on
spec:
  containers:
  - args:
    - kong
    - migrations
    - bootstrap
    env:
    - name: KONG_DATABASE
      value: postgres
    - name: KONG_PG_HOST
      value: kong-db-on
    - name: KONG_PG_PASSWORD
      value: kongPassword123
    - name: KONG_PG_USER
      value: kongUser
    image: kong:latest
    name: kong-db-migrations-on
    resources: {}
  restartPolicy: OnFailure
status: {}
