apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kong-db-on
  name: kong-db-on
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kong-db-on
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/kong-net: "true"
        io.kompose.service: kong-db-on
    spec:
      containers:
      - env:
        - name: POSTGRES_MULTIPLE_DATABASES
          value: kong,konga
        - name: POSTGRES_PASSWORD
          value: kongPassword123
        - name: POSTGRES_USER
          value: kongUser
        image: postgres:9.6
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - kongUser
          failureThreshold: 5
          periodSeconds: 5
          timeoutSeconds: 5
        name: kong-db-on
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
