apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_HOST
            value: postgres
          - name: KONG_PG_USER
            value: postgresadmin
          - name: KONG_PG_PASSWORD
            value: 3c5303d6-b50d
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr