apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "8444"
      port: 8444
      targetPort: 8444
  selector:
   app: kong

# kubectl create -f 01-kong-deployment.yaml
# kubectl create -f 02-kong-service.yaml

# kubectl get svc kong
# kubectl get pods
# kubectl logs kong-75c867b8dc-dj9r8