apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres

# kubectl create -f 01-postgres-configmap.yaml 
# kubectl create -f 02-postgres-storage.yaml 
# kubectl create -f 03-postgres-statefulset.yaml
# kubectl create -f 04-postgres-service.yaml 

# kubectl get svc postgres

# kubectl delete service postgres 
# kubectl delete deployment postgres
# kubectl delete configmap postgres-config
# kubectl delete persistentvolumeclaim postgres-pv-claim
# kubectl delete persistentvolume postgres-pv-volume